[tool.ruff]
# Never enforce `E501` (line length violations).
ignore = ["C901", "E501", "E741", "F402", "F823" ]
select = ["C", "E", "F", "I", "W"]
line-length = 119

# Ignore import violations in all `__init__.py` files.
[tool.ruff.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403", "F811"]
"src/transformers/file_utils.py" = ["F401"]
"src/transformers/utils/dummy_*.py" = ["F401"]

[tool.ruff.isort]
lines-after-imports = 2
known-first-party = ["transformers"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.pytest.ini_options]
doctest_optionflags="NUMBER NORMALIZE_WHITESPACE ELLIPSIS"
doctest_glob="**/*.md"
# addopts = "-rA -s -m 'not (not_device_test or require_ray or require_torch_up_to_2_gpus or require_torch_multi_gpu or require_torch_gpu or require_torch_non_multi_gpu or require_torch_bf16_gpu or require_torch_tf32 or require_torch_npu or require_torch_multi_npu or require_torch_neuroncore or require_torch_tensorrt_fx or require_pytorch_quantization or require_apex or require_tf or require_flax or require_torch_xla or torch_fx or require_detectron2 or require_flash_attn or flash_attn_test or require_bitsandbytes or require_quanto or require_auto_gptq or require_auto_awq or require_aqlm or require_natten)' -k 'not (tpu or cuda or npu or flax or tf)'"
markers = [
    "flash_attn_test: marks tests related to flash attention (deselect with '-m \"not flash_attn_test\"')",
    "bitsandbytes: select (or deselect with `not`) bitsandbytes integration tests",
]
env = [
    "RUN_SLOW = 1",
    "TRANSFORMERS_TEST_DEVICE = xpu",
    "TRANSFORMERS_TEST_DEVICE_SPEC = spec.py",
    "RUN_PIPELINE_TESTS = True",
    "RUN_PT_TF_CROSS_TESTS = False",
    "RUN_PT_FLAX_CROSS_TESTS = False",
    "OMP_NUM_THREADS = 1"
]
